---
name: run-hello
description: "Rule to run hello world"
enabled: true

trigger:
  description: "Triggers on specified intervals. e.g. every 30s, 1week etc."
  type: core.st2.webhook
  parameters:
    url: "rozman"

criteria:
  trigger.body.action:
    type: equals
    pattern: "add"
    

action:
  ref: amdocs_st2_training.add_numbers_action_python
  description: "Action for adding numbers "
  parameters:
    json_data: "{{ trigger.body }}"

