---
name: "add_numbers_timer_rule"                      # required
pack: "amdocs_st2_training"                       # optional
description: "Rule description."       # optional
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
      unit: "seconds"
      delta: 10

action:
    ref: "amdocs_st2_training.add_numbers_action_python"
    parameters:
      num1: 1
      num2: 2