---
name: "add_numbers_webhook_rule"                      # required
pack: "amdocs_st2_training"                       # optional
description: "Rule description."       # optional
enabled: true

trigger:
        type: "core.st2.webhook"
        parameters:
            url: "rozman"

criteria:
    trigger.body.action:
        type: "equals"
        pattern: "add"

action:
    ref: "amdocs_st2_training.add_numbers_action_python"
    parameters:
      num1: "{{ trigger.body.num1 }}"
      num2: "{{ trigger.body.num2 }}"


